name: Lint and Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v /tmp/runner/work/flourish-2023/flourish-2023:/tmp -w /tmp node:16-alpine "npm install && npm run lint"

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v /tmp/runner/work/flourish-2023/flourish-2023:/tmp -w /tmp node:16-alpine "npm install && npm run build"
