name: Lint and Build

runs-on: self-hosted
on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    steps:
      - uses: actions/checkout@v3
      - run: echo 'TODO: Add linting'

  build:
    steps:
      - uses: actions/checkout@v3
      - run: echo "TODO: Add building"
