name: Lint and Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "Add linting"

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "Add building"
